name: Build Windows Only

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build Windows executable
      run: |
        pyinstaller --onefile --windowed --name=FlipField_Analysis --icon=src/flip612x612.png src/FlipFieldGUI.py

    - name: Prepare Windows artifact
      run: |
        copy dist\FlipField_Analysis.exe FlipField_Analysis_Windows.exe
        copy DISTRIBUTION_README.md dist\

    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: |
          FlipField_Analysis_Windows.exe
          DISTRIBUTION_README.md 